// Ready designs shown on the homepage.
// Prices are PLACEHOLDERS — confirm with the Kharbesh team before going live.
export const READY_DESIGNS = [
  {
    id: 'podcats',
    img: '/assets/designs/podcats.png',
    title_en: 'Podcasts',
    title_ar: 'بودكاتس',
    world_en: 'Kharbesh Jomal',
    world_ar: 'خربش جمل',
    code: 'KH-001',
    price: 24,
  },
  {
    id: 'ya-ammi',
    img: '/assets/designs/ya-ammi.png',
    title_en: 'Ya Ammi',
    title_ar: 'يا عمي',
    world_en: 'Kharbesh Jomal',
    world_ar: 'خربش جمل',
    code: 'KH-002',
    price: 24,
  },
  {
    id: 'memo',
    img: '/assets/designs/memo.png',
    title_en: 'Urgent Request',
    title_ar: 'طلب عاجل',
    world_en: 'Kharbesh Siyeseh',
    world_ar: 'خربش سياسة',
    code: 'KH-003',
    price: 24,
  },
  {
    id: 'hayyana',
    img: '/assets/designs/hayyana.png',
    title_en: 'The Hayyana',
    title_ar: 'الحيونة',
    world_en: 'Kharbesh Jomal',
    world_ar: 'خربش جمل',
    code: 'KH-004',
    price: 24,
  },
  {
    id: 'paperboat',
    img: '/assets/designs/paperboat.png',
    title_en: 'Paper Boat',
    title_ar: 'قارب ورق',
    world_en: 'Kharbesh Rahbaniyyat',
    world_ar: 'خربش رحبانيّات',
    code: 'KH-005',
    price: 26,
  },
  {
    id: 'door',
    img: '/assets/designs/door.png',
    title_en: 'Your Opinion?',
    title_ar: 'هيدا رأيك؟',
    world_en: 'Kharbesh Jomal',
    world_ar: 'خربش جمل',
    code: 'KH-006',
    price: 24,
  },
];
